services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: financial_management
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - app-network

  spring-boot-app:
    image: firstproject
    container_name: spring-boot-app
    depends_on:
      - mysql-db
    ports:
      - "8080:8080"
    environment:
          SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/financial_management
          SPRING_DATASOURCE_USERNAME: user
          SPRING_DATASOURCE_PASSWORD: password
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
